title: CostManagement Docs
logoText: CostManagement Docs
lang: zh
api:
  crds:
    - docs/shared/crds/*.yaml
  openapis:
    - docs/shared/openapis/*.json
# 以下资源文件路径，相对于 doom.config.yaml 所在目录，支持 glob 匹配，json/yaml 文件
permission:
  functionresources:
    - docs/shared/functionresources/*.yaml
  roletemplates:
    - docs/shared/roletemplates/*.yaml

releaseNotes:
  queryTemplates:
    unfixed: |
      filter = 18959 AND (affectedVersion not in versionMatch("v4.[1-9]|v4.0.[1-9]|-v[0-9]") OR ACPAffectVersions in (v4.0.0)) AND ((fixVersion not in versionMatch(v3.) OR fixVersion is EMPTY OR ACPFixVersions in (v4.0.0)) AND (status not in (Closed, Done, Resolved, 已验证, Cancelled) OR status = Cancelled AND (affectedVersion in versionMatch(v4.0.0) OR ACPAffectVersions in (v4.0.0))) OR status in (Closed, Done, Resolved, 已验证) AND (fixVersion in versionMatch("v4.0.[1-9]|v4.[1-9]") OR ACPFixVersions in (v4.0.1, v4.1.0)) OR resolved >= 2025-04-02 AND (fixVersion in versionMatch(v4.0.0) OR fixVersion is EMPTY OR ACPFixVersions in (v4.0.0) OR ACPFixVersions is EMPTY) AND status in (Cancelled, Resolved)) AND (labels in (bug_clone, auto_clone) AND affectedVersion in versionMatch(v4.0.0) OR labels not in (bug_clone, auto_clone) OR labels is EMPTY) AND (labels not in (非产品问题, 非当前版本功能, 安全问题) OR labels is EMPTY) AND project = AIT and ReleaseNotesStatus = Publish   and project = AIT  AND Feature = "AIT - 计量计费"